language: java
jobs:
  include:
    - stage: automatic performance tests on staging
      script:
        - cd ..
        - "git clone https://github.com/mischi33/MusicMatchBackendTest.git"
        - cd MusicMatchBackendTest
        - mvn verify
        - cd ..
        - "git clone https://github.com/mischi33/MusicMatchBackendDocs.git"
        - rm -rf MusicMatchBackendDocs/generated/jmeter
        - cp -r MusicMatchBackendTest/target/jmeter/reports/performance* MusicMatchBackendDocs/generated/jmeter
        - cd MusicMatchBackendDocs
        - git add --all
        - git commit -am "update jmeter documentation"
        - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/mischi33/MusicMatchBackendDocs.git" master